//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DnD.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_DND_FORM                    101
#define IDD_MAPPLAYVIEW                 101
#define IDD_CONNVIEW                    102
#define IDD_CHATVIEW                    103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_DNDTYPE                     129
#define IDD_DLGPLAYERSET                131
#define IDD_DLGHEADCHOOSE               132
#define IDB_DEFHEAD                     133
#define IDD_DLGCREATEPLAYER             134
#define IDB_INFO                        136
#define IDD_PROFMANAGERDLG              138
#define IDD_ADDPROFILE                  140
#define IDB_SKETCH                      143
#define IDD_CHATOPTIONSDLG              144
#define IDB_PAGETITLE                   146
#define IDC_IPADDRESS                   1000
#define IDC_EDITPORT                    1001
#define IDC_EDITUSERNAME                1002
#define IDC_BUTTONCONNECT               1003
#define IDC_LISTCONN                    1004
#define IDC_LISTCHAT                    1005
#define IDC_BUTTONSEND                  1006
#define IDC_EDITCHAT                    1007
#define IDC_SKETCHBLCOK                 1008
#define IDC_DEBUGBTN                    1009
#define IDC_PLAYERSET                   1010
#define IDC_CHOOSEHEAD                  1011
#define IDC_HEAD1                       1012
#define IDC_HEAD2                       1013
#define IDC_HEAD3                       1014
#define IDC_HEAD4                       1015
#define IDC_HEAD5                       1016
#define IDC_HEAD6                       1017
#define IDC_HEAD7                       1018
#define IDC_HEAD8                       1019
#define IDC_HEAD9                       1020
#define IDC_HEAD10                      1021
#define IDC_NEXTHEAD                    1022
#define IDC_PREVHEAD                    1023
#define IDC_HEAD                        1023
#define IDC_EDITPASS                    1024
#define IDC_HEADCHOSEN                  1024
#define IDC_COMBOCHARS                  1025
#define IDC_STATNAME                    1026
#define IDC_STATCLASS                   1027
#define IDC_CHARNAME                    1028
#define IDC_GENDER                      1031
#define IDC_BTNPORTRAIT                 1032
#define IDC_CLASS                       1035
#define IDC_STATGENDER                  1036
#define IDC_RACE                        1036
#define IDC_STR                         1037
#define IDC_DEX                         1038
#define IDC_CON                         1039
#define IDC_INT                         1040
#define IDC_WIS                         1041
#define IDC_CHA                         1042
#define IDC_GENSTATS                    1043
#define IDC_STRMOD                      1044
#define IDC_DEXMOD                      1045
#define IDC_CONMOD                      1046
#define IDC_INTMOD                      1047
#define IDC_WISMOD                      1048
#define IDC_CHAMOD                      1049
#define IDC_ALIGNMENT                   1050
#define IDC_DEITY                       1051
#define IDC_FAMILIAR                    1052
#define IDC_STATFAM                     1053
#define IDC_AGE                         1054
#define IDC_LANGUAGES                   1055
#define IDC_LANG                        1056
#define IDC_FORT                        1057
#define IDC_HITPOINTS                   1058
#define IDC_AC                          1059
#define IDC_STATAGE                     1059
#define IDC_STATALIGNMENT               1060
#define IDC_REFLEX                      1061
#define IDC_STATDEITY                   1061
#define IDC_WILL                        1062
#define IDC_STATDESCRIPTION             1062
#define IDC_INITIATIVE                  1063
#define IDC_STATRACE                    1063
#define IDC_MELEE                       1064
#define IDC_RANGED                      1065
#define IDC_INFO                        1066
#define IDC_GENRAND                     1067
#define IDC_INFO2                       1067
#define IDC_DESC                        1068
#define IDC_NEWCHAR                     1069
#define IDC_CONNPROFILE                 1070
#define IDC_USERPROFILE                 1071
#define IDC_PROFMANAGER                 1072
#define IDC_FILE                        1074
#define IDC_PROFILES                    1075
#define IDC_ADD                         1076
#define IDC_CHANGE                      1077
#define IDC_DELETE                      1078
#define IDC_SERVIP                      1081
#define IDC_PROFNAME                    1082
#define IDC_USERNAME                    1083
#define IDC_PASS                        1084
#define IDC_BROWSEFILE                  1084
#define IDC_SAVECHANGES                 1085
#define IDC_CHANGEPATH                  1086
#define IDC_STATFILE                    1087
#define IDC_UNOWNED                     1088
#define IDC_EDITUNCHAR                  1089
#define IDC_STATSTR                     1090
#define IDC_STATDEX                     1091
#define IDC_STATCON                     1092
#define IDC_STATINT                     1093
#define IDC_STATWIS                     1094
#define IDC_STATCHA                     1095
#define IDC_MAPAREA                     1096
#define IDC_DEBUGBTN2                   1097
#define IDC_HEADME                      1098
#define IDC_CHARN1                      1099
#define IDC_CHARN2                      1100
#define IDC_CHARN3                      1101
#define IDC_CHARN4                      1102
#define IDC_CHARN5                      1103
#define IDC_CHARN6                      1104
#define IDC_CHARN7                      1105
#define IDC_CHARN8                      1106
#define IDC_CHATOPTIONS                 1107
#define IDC_RES                         1108
#define IDC_SPINRES                     1111
#define IDC_LIST1                       1112
#define IDC_MAPCHAT                     1113
#define IDC_BTNCHAT                     1114
#define ID_CONNECT                      32771
#define ID_CHAT                         32772
#define ID_MAPPLAY                      32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
