//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DnD.rc
//
#define IDKICK                          2
#define IDBAN                           3
#define IDD_ABOUTBOX                    100
#define IDD_DND_FORM                    101
#define IDD_CONNVIEW                    102
#define IDD_CHATVIEW                    103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_SKETCHVIEW                  104
#define CG_IDR_POPUP_CHAT_VIEW          105
#define IDD_MAPVIEW                     105
#define CG_IDD_PROGRESS                 106
#define CG_IDS_PROGRESS_CAPTION         107
#define IDR_MAINFRAME                   128
#define IDR_DNDTYPE                     129
#define IDB_HEAD5                       132
#define IDB_HEAD1                       133
#define IDB_DEFHEAD                     133
#define IDB_HEAD2                       134
#define IDB_HEAD3                       135
#define IDB_HEAD4                       136
#define IDB_LINE                        138
#define IDB_CIRCLE                      139
#define IDB_SELECT                      140
#define IDI_ICON1                       141
#define IDB_BLANKROOM                   145
#define IDD_MAPSETDLG                   147
#define IDD_MAPPLAY                     148
#define IDB_INFO                        153
#define TILE_ROOM                       156
#define TILE_CORRIDOR                   158
#define TILE_HERO                       162
#define TILE_PARTY                      163
#define TILE_FURNITURE                  165
#define TILE_PIT                        166
#define TILE_TREASURE                   167
#define IDD_STATSDIALOG                 170
#define IDB_BCKGRND                     177
#define IDB_PAGETITLE                   180
#define IDC_BTN_STARTSVR                1000
#define IDC_SVRSTATLIST                 1002
#define IDC_PORT                        1003
#define CG_IDC_PROGDLG_PROGRESS         1003
#define IDC_SVRSTATLIST2                1004
#define CG_IDC_PROGDLG_PERCENT          1004
#define IDC_CHATBOX                     1005
#define CG_IDC_PROGDLG_STATUS           1005
#define IDC_SENDCHAT                    1006
#define IDC_BUTTONSEND                  1007
#define IDC_USERLIST                    1008
#define IDC_COMMANDBOX                  1009
#define IDC_HEAD1                       1012
#define IDC_HEAD2                       1013
#define IDC_SKETCHBLOCK                 1013
#define IDC_HEAD3                       1014
#define IDC_SKETCHBLOCK2                1014
#define IDC_HEAD4                       1015
#define IDC_LINETOOL                    1015
#define IDC_HEAD5                       1016
#define IDC_CIRCLETOOL                  1016
#define IDC_HEAD6                       1017
#define IDC_SELECTTOOL                  1017
#define IDC_HEAD7                       1018
#define IDC_COLPICKOUT                  1018
#define IDC_HEAD8                       1019
#define IDC_COLPICKIN                   1019
#define IDC_TRANSCHECK                  1020
#define IDC_CLEAR                       1021
#define IDC_CHECK2                      1022
#define IDC_LIVEUPDATE                  1022
#define IDC_CHECKNAME2                  1022
#define IDC_SENDIMAGE                   1023
#define IDC_BTIMEOUT                    1024
#define IDC_BL1                         1027
#define IDC_MAP                         1028
#define IDC_BL2                         1031
#define IDC_BL3                         1032
#define IDC_BL4                         1033
#define IDC_ROOMTOOL                    1033
#define IDC_BL5                         1034
#define IDC_TOOLCORRIDOR                1034
#define IDC_BL6                         1035
#define IDC_BL7                         1036
#define IDC_SETTINGS                    1037
#define IDC_BL8                         1038
#define IDC_BLOCKS                      1039
#define IDC_BL9                         1040
#define IDC_SPIN1                       1040
#define IDC_BL10                        1041
#define IDC_BL11                        1042
#define IDC_BL12                        1043
#define IDC_ROOMCOMBO                   1043
#define IDC_BL13                        1044
#define IDC_CURRENTTOOL                 1044
#define IDC_BL14                        1045
#define IDC_TOOLDOOR                    1045
#define IDC_BL15                        1046
#define IDC_DOORCOMBO                   1046
#define IDC_BL16                        1047
#define IDC_UNDO                        1047
#define IDC_BL17                        1048
#define IDC_ERASER                      1048
#define IDC_BL18                        1049
#define IDC_DISPGRID                    1049
#define IDC_BL19                        1050
#define IDC_CLEARBUTTON                 1050
#define IDC_BL20                        1051
#define IDC_ITEMS                       1051
#define IDC_ITEMSCOMBO                  1052
#define IDC_CLEARMAP                    1053
#define IDC_SAVEMAP                     1054
#define IDC_LOADMAP                     1055
#define IDC_MAPNAME                     1056
#define IDC_PLAYERS                     1058
#define IDC_COMBOPLAYERS                1059
#define IDC_TOOLSELECT                  1060
#define IDC_MONSTER                     1061
#define IDC_BL21                        1062
#define IDC_COMBOMONSTER                1062
#define IDC_BL22                        1063
#define IDC_DELETESM                    1063
#define IDC_BL23                        1064
#define IDC_STATINFOBL                  1064
#define IDC_BL24                        1065
#define IDC_STATINFOBL2                 1065
#define IDC_CHECKHIRES                  1065
#define IDC_BL25                        1066
#define IDC_STATINFOBL3                 1066
#define IDC_BL26                        1067
#define IDC_LAYERCOMBO                  1067
#define IDC_BL27                        1068
#define IDC_STATDEB                     1068
#define IDC_BL28                        1069
#define IDC_BL29                        1070
#define IDC_BL30                        1071
#define IDC_VISCOMBO                    1071
#define IDC_BL31                        1072
#define IDC_BL32                        1073
#define IDC_CHECKNAME                   1073
#define IDC_BL33                        1074
#define IDC_UP                          1074
#define IDC_BL34                        1075
#define IDC_RIGHT                       1075
#define IDC_BL35                        1076
#define IDC_LEFT                        1076
#define IDC_CHECKCP                     1076
#define IDC_BL36                        1077
#define IDC_DOWN                        1077
#define IDC_BL37                        1078
#define IDC_STATMAPTITLE                1078
#define IDC_BL38                        1079
#define IDC_UNHIDE                      1079
#define IDC_BL39                        1080
#define IDC_COMBOAREA                   1080
#define IDC_BL40                        1081
#define IDC_Start                       1082
#define IDC_USERNAME                    1083
#define IDC_CHARNAME                    1084
#define IDC_STRENGTH                    1086
#define IDC_DEXTERITY                   1087
#define IDC_CONSTITUTION                1088
#define IDC_INTELLIGENCE                1089
#define IDC_WISDOM                      1090
#define IDC_CHARISMA                    1091
#define IDC_ARMOR                       1093
#define IDDOCHANGES                     1094
#define IDC_GIF1                        1097
#define IDC_GIF2                        1098
#define IDC_BUTTON1                     1098
#define IDC_LOADIMAGEBTN                1099
#define IDC_COLIN                       1100
#define IDC_COLOUT                      1101
#define IDC_CHATINMAP                   1101
#define IDC_CHATMAP                     1102
#define IDC_CHATSEND                    1103
#define IDC_IP1                         1105
#define IDC_CONHOST                     1107
#define IDC_Link                        1108
#define IDC_BTNSEND                     1109
#define IDC_EDITTOSENDCHAT              1110
#define ID_CONNECT                      32771
#define ID_CHAT                         32772
#define ID_POPUP_WHISPER                32773
#define ID_POPUP_KICK                   32774
#define ID_SKETCH                       32775
#define ID_POPUP_PLAYERSTATS            32778
#define ID_POPUP_BAN                    32783
#define ID_MAP                          32784
#define ID_MAPPLAY                      32785
#define ID_BUTTON32786                  32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        181
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1111
#define _APS_NEXT_SYMED_VALUE           108
#endif
#endif
